import string

suspicious_tempmail_nameservers = [
  ".dnsowl.com", # temp-mail.org
]

trusted_mx_servers = [
  "alt1.aspmx.l.google.com",
  "alt2.aspmx.l.google.com",
  "alt3.aspmx.l.google.com",
  "alt4.aspmx.l.google.com",
  "aspmx.l.google.com",
  "aspmx2.googlemail.com",
  "aspmx3.googlemail.com",
  "aspmx4.googlemail.com",
  "aspmx5.googlemail.com",
  "alt1.gmail-smtp-in.l.google.com",
  "alt2.gmail-smtp-in.l.google.com",
  "alt3.gmail-smtp-in.l.google.com",
  "alt4.gmail-smtp-in.l.google.com",
  "gmail-smtp-in.l.google.com"
  ".mail.protection.outlook.com",
  ".olc.protection.outlook.com",
  "mx-eu.mail.am0.yahoodns.net",
  "mta7.am0.yahoodns.net",
  "mta6.am0.yahoodns.net",
  "mta5.am0.yahoodns.net",
  "mail.protonmail.ch",
  "mailsec.protonmail.ch",
  ".emig.gmx.net",
]

# https://www.usercheck.com/providers
tempmail_mx_servers = [
  "mx2.den.yt",
  "mx1.icdn.be",
  "generator.email",
  "tempm.com",
  "emailfake.com",
  "email-fake.com",
  "mail.ggez.team",
  "mx.cse445.com",
  "mx1.simplelogin.co",
  "mx2.simplelogin.co",
  "smtp.yopmail.com",
  "gpa.lu",
  "mail.anonaddy.me",
  "mail2.anonaddy.me",
  "inbound-smtp.skiff.com",
  "in.mail.tm",
  "mx.discard.email",
  "mx.moakt.com",
  "mx.temp-mail.io",
  "mx2.temp-mail.io",
  "prd-smtp.10minutemail.com",
  "loti3.papierkorb.me",
  "us2.mx1.mailhostbox.com",
  "us2.mx2.mailhostbox.com",
  "us2.mx3.mailhostbox.com",
  "mail.mailinator.com",
  "mail2.mailinator.com",
  "mailnesia.com",
  "mx.1secmail.com",
  "mail.h-email.net",
  "mxa.mailgun.org",
  "mxb.mailgun.org",
]

public_email_providers = [
  "aol.com",
  "att.net",
  "bellsouth.net",
  "charter.net",
  "comcast.net",
  "cox.net",
  "duck.com",
  "earthlink.net",
  "fastmail.com",
  "free.fr",
  "gmail.com",
  "googlemail.com",
  "gmx.com",
  "gmx.es",
  "gmx.net",
  "hey.com",
  "hotmail.ca",
  "hotmail.cl",
  "hotmail.co.uk",
  "hotmail.com",
  "hotmail.es",
  "hotmail.it",
  "hotmail.fr",
  "icloud.com",
  "juno.com",
  "live.ca",
  "live.cl",
  "live.com",
  "live.com.ar",
  "live.com.mx",
  "live.fr",
  "mac.com",
  "mail.com",
  "mail.ru",
  "me.com",
  "mindspring.com",
  "msn.com",
  "mozmail.com",
  "netzero.net",
  "orange.fr",
  "outlook.com",
  "outlook.es",
  "outlook.pt",
  "pm.me",
  "proton.com",
  "proton.me",
  "protonmail.com",
  "qq.com",
  "rediffmail.com",
  "rocketmail.com",
  "tutamail.com",
  "tutanota.com",
  "verizon.net",
  "myyahoo.com",
  "yahoo.ca",
  "yahoo.cl",
  "yahoo.co.uk",
  "yahoo.com",
  "yahoo.es",
  "yahoo.fr",
  "ymail.com",
  "yandex.com",
  "zoho.com",
  "zohomail.com",
]

tempmail_domains = [
  "tempmail.cn",
]

typos_gmail = [
  "agmail.com",
  "amil.com",
  "bmail.com",
  "cmail.com",
  "com.gmail",
  "dmail.com",
  "egameil.com",
  "emeil.com",
  "emagil.com",
  "emial.com",
  "fmail.com",
  "fgmail.com",
  "g20mail.com",
  "gaali.com",
  "gail.co",
  "g.ail.com",
  "ga.il.com",
  "gailme.com",
  "gaimil.com",
  "gaiml.com",
  "galim.com",
  "gamal.com",
  "gamail.com",
  "gameil.com",
  "gamial.com",
  "gami.com",
  "gamik.com",
  "gamil.ccom",
  "gamil.com",
  "gamil.com.br",
  "gamil.cm",
  "gamilm.com",
  "gamli.com",
  "gamol.com",
  "gamul.com",
  "gatmail.com",
  "gemai.com",
  "gemaik.com",
  "ge-mail.com",
  "gemal.com",
  "gemale.com",
  "geme.com",
  "gemei.com",
  "gemeil.com",
  "gemeio.com",
  "gemeioo.com",
  "gemil.com",
  "gemil.com.pe",
  "geml.com",
  "gemail.com",
  "ggjail.com",
  "ggmail.com",
  "ghmail.com",
  "ghmel.com",
  "giail.com",
  "gilam.com",
  "gilm.com",
  "gim.com",
  "gimael.com",
  "gimai.com",
  "gimail.com",
  "gimal.co.com",
  "gimal.com",
  "gimall.com",
  "gimeil.com",
  "gimeilll.com",
  "gimil.com",
  "gkail.com",
  "gma8l.com",
  "gmae.com",
  "gmaei.com",
  "gmael.com",
  "gmai.co",
  "gmai.com",
  "gmaii.com",
  "gmaiil.com",
  "gmaiil.com.com",
  "gmaiel.com",
  "g.mail",
  "gmail.cam",
  "gmail.cim",
  "gmail.cl",
  "gmail.cm",
  "gmail.co",
  "gmail.co.com",
  "gmailgmail.com",
  "g.mail.com",
  "gmail.com.ar", # !
  "gmail.com.br", # !
  "gmailcom.br",
  "gmail.com.email",
  "gmails.com",
  "gmail.br",
  "gmail.coml",
  "gmail.com.pe",
  "gmail.con",
  "gmail.con.ar",
  "gmail.coom",
  "gmaile.com",
  "gmailg.com",
  "gmaili.com",
  "gmail.l.com",
  "gmailm.com",
  "gmail.hot",
  "gmail.mx",
  "gmail.net",
  "gmail.om",
  "gmail.su",
  "gmaill.com",
  "gmaim.com",
  "gmain.com",
  "gmaio.com",
  "gmaiol.com",
  "gmaip.com",
  "gmaisl.com",
  "gmajl.com",
  "gmakl.com",
  "gmal.com.br",
  "gmall.co",
  "gmalli.com",
  "gmamail.com",
  "gmaol.com",
  "gmaoo.com",
  "gmasil.com",
  "gmauil.com",
  "gmay.com",
  "gmei.com",
  "gmeil.com",
  "gmeli.com",
  "gmel.com",
  "gmell.com",
  "gmeio.com",
  "gmiaal.com",
  "gmiel.com",
  "gmil.ci",
  "gmil.co",
  "gmil.com",
  "gmil.cm",
  "gmilcom.com",
  "gmilcom.com",
  "gmill.com",
  "gmill.con",
  "gmlail.com",
  "gml.com",
  "gmli.com",
  "gmlil.com",
  "gmoil.com",
  "gmqil.com",
  "gmqul.com",
  "gmrail.com",
  "gmsil.com",
  "gmsip.com",
  "gmso.com",
  "gmulan.com",
  "gmwil.com",
  "gmwol.com",
  "gmzil.com",
  "gnaik.com",
  "gnail.com",
  "golmail.com",
  "gomail.com",
  "gomil.com",
  "gotgamail.com",
  "gpail.com",
  "gqmil.com",
  "gtmai.com",
  "gtmail.com",
  "guiel.com",
  "guimei.com",
  "guimaill.com",
  "hemail.com",
  "hmail.com",
  "iemil.com",
  "igmail.com",
  "igmil.com",
  "imail.com",
  "imalg.com",
  "imalg.con",
  "jimail.com",
  "jmail.com",
  "jeml.com",
  "magi.com",
  "maill.com",
  "mailg.com",
  "mgail.com",
  "oegmail.com",
  "omagil.com",
  "ogmail.com",
  "sgmail.com",
  "tmail.com",
  "tgmail.com",
  "vmail.com",
  "www.gmail.com",
  "xn--gmai-3oa.com",
  "xn--gmai-jqa.com",
  "xn--gmai-opa.com",
  "xn--gmai-y0a.com",
]

typos_hotmail = [
  "ghotmail.com",
  "gotmail.com",
  "hitmail.com",
  "hitmsil.com",
  "hitnail.com",
  "hltmail.com",
  "hoail.com",
  "hotmao.com",
  "hotmat.com",
  "hoatmail.com",
  "hogmail.com",
  "hogmai.com",
  "hoimail.com",
  "hojmail.com",
  "holmail.com",
  "holmai.com",
  "homail.com",
  "homait.com",
  "hormail.com",
  "hortmail.com",
  "hotail.com",
  "hotamul.com",
  "hotemail.com",
  "hotlail.com",
  "hotmael.com",
  "hotmai.com",
  "hotmaiel.com",
  "hotmaii.com",
  "hotmail.c.com",
  "hotmail.co.com",
  "hotimal.com",
  "hotimail.com.mx",
  "higmail.co.com",
  "hotmail.cm",
  "hotmail.con",
  "hotmailm.com",
  "hotmmail.com",
  "hotmaim.com",
  "hotmaio.com",
  "hotmaip.com",
  "hotmaul.com",
  "hotmil.com",
  "hotml.com",
  "hotnal.com",
  "hotnaul.com",
  "hoymail.com",
  "hoy.ail.com",
  "jhomil.com",
  "jhtmail.com",
  "jomail.com",
  "jotmail.com",
  "jotm.com",
  "jptmail.com",
  "otmai.com",
  "rotmail.com",
  "votmail.com",
  "xn--hotmai-1wa.com",
]

typos_icloud = [
  "iphone.com", # MX redirects to 127.0.0.6
  "ickoud.com",
  "iclaud.com",
  "icliud.com",
  "iclod.com",
  "iclond.com",
  "iclou.com",
  "icloud.ca",
  "icloud.cl",
  "icloud.cloud",
  "icloud.cm",
  "icloud.co",
  "icloud.net",
  "i.cloud.com",
  "icloud.con",
  "iclouf.com",
  "iclould.com",
  "iclound.com",
  "icloup.com",
  "iclout.com",
  "iclud.com",
  "icluod.com",
  "icooud.com",
  "icoud.co.com",
  "icloud.co.com",
  "icoud.com",
  "idoud.com",
  "ifloud.com",
  "ilcoud.com",
  "ivloud.com",
  "jcloud.com",
  "ocloud.com",
]

typos_yahoo = [
  "uahoo.com",
  "hahoo.com",
  "yqhoo.com",
  "yahool.com",
  "yagoo.com",
]

typos_outlook = [
  "putlook.com",
  "iutlook.com",
  "eutlook.com",
  "otlook.com",
  "outlok.com",
  "oulook.com",
  "outkook.com",
  "outllok.com",
  "outloo.com",
  "outloom.com",
  "outlool.com",
  "outlook.gov",
  "outlosk.com",
  "oooutlook.com",
  "otublook.com",
  "utlook.com",
  "youtlook.com",
]

typos_gmx = [
  "gnx.com",
]

domain_typos = {
  "gmail.com": typos_gmail,
  "hotmail.com": typos_hotmail,
  "icloud.com": typos_icloud,
  "yahoo.com": typos_yahoo,
  "outlook.com": typos_outlook,
  "gmx.com": typos_gmx,
}

def generate_typos(word):
  typos = [f"{word}{word}"]
  for i, char in enumerate(word):
    for replacement in string.ascii_lowercase:
      if char != replacement:
        typos.append(word[:i] + replacement + word[i+1:])
  return typos

tld_typos = {
  "com": generate_typos("com"),
  "net": generate_typos("net"),
  "org": generate_typos("org"),
}